### ISSUE TITLE
LAMMPS not recognizing src file

### ISSUE THREAD

**Issue by anneb101** [zhenxingwang/lammps-conp#1]
Hello, 
I followed the instructions of copying fix_conp.h and fix_conp.cpp to the lammps src directory, as well as to a folder "fix_conp" that I created in the src directoroy. When I ran the command "make yes-fix_conp", LAMMPS could not recognize the package fix_conp. How would you recommend going about this compilation so that fix_comp is included?
Thanks,
Anne

**Comment by zhenxingwang** [comment]
Hi Anne,
fix_conp is not a standard package of lammps so "make yes-xxx" command is not required. Just copy the files to src directory and compile lammps. Please refer to "installation“ section of README.
