### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by fcannini** [zhenxingwang/lammps-conp#3]
I was compiling this fix today and noticed this strangely named variable:
https://github.com/zhenxingwang/lammps-conp/blob/5c0518dc5da7d4a26aa59b9dda8c4ae5d1c6c755/fix_conp.h#L65

https://github.com/zhenxingwang/lammps-conp/blob/5c0518dc5da7d4a26aa59b9dda8c4ae5d1c6c755/fix_conp.cpp#L69

[ ]'s

**Comment by zhenxingwang** [comment]
Corrected. Thank you.
