### ISSUE TITLE
Seg fault. Memory issue?

### ISSUE THREAD

**Issue by Mounika-G** [zhenxingwang/lammps-conp#6]
Hi,
I tried to run the 'example_input' script on a cluster with maximum RAM ~ 512 GB. The programs halts after just one step, printing segmentation fault. Can you suggest me a way to fix this?

Thanks,
Mounika Gosika
Dept. of Physics
IISc Bangalore - 560012.

**Comment by LangLuke** [comment]
Hi Mounika,

I am running into a very similar problem and am wondering how you solved it. The example_input script executes fine for me, but when using fix_conp on my own simulation it halts after just one step, printing segmentation fault as well.

Thanks.

**Comment by Mounika-G** [comment]
Hi LangLuke,

I took help from our computational facility staff. I am just briefing you about what they did. You can try linking '-ltbbmalloc' along with the LAPACK and BLAS libraries while building the LAMMPS executable. Hope this will solve the issue.

Good luck!
